// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDALRollUlTXDdc2dNBg-cWrTWgVBrBbPk',
    appId: '1:918797848192:web:f6d7bdad3e377801d1e065',
    messagingSenderId: '918797848192',
    projectId: 'quran-app-485bd',
    authDomain: 'quran-app-485bd.firebaseapp.com',
    storageBucket: 'quran-app-485bd.appspot.com',
    measurementId: 'G-ZH5MGLFYZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhaGBcwTUHa6XBr9IrYjIackPSScy6pw0',
    appId: '1:918797848192:android:7a6b2a1098a66377d1e065',
    messagingSenderId: '918797848192',
    projectId: 'quran-app-485bd',
    storageBucket: 'quran-app-485bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDePSXroVDV3ofz3acIRYpOZJiCGVGYpHk',
    appId: '1:918797848192:ios:da956cfc311274fdd1e065',
    messagingSenderId: '918797848192',
    projectId: 'quran-app-485bd',
    storageBucket: 'quran-app-485bd.appspot.com',
    iosBundleId: 'com.hamdy.qurankarimapp.quranApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDePSXroVDV3ofz3acIRYpOZJiCGVGYpHk',
    appId: '1:918797848192:ios:85dc4f7a246687d9d1e065',
    messagingSenderId: '918797848192',
    projectId: 'quran-app-485bd',
    storageBucket: 'quran-app-485bd.appspot.com',
    iosBundleId: 'com.hamdy.qurankarimapp.quranApp.RunnerTests',
  );
}
